### PR TITLE
Update Firefox and geckodriver

### PR DESCRIPTION
**Pull request by thc202**
Update Firefox (75.0) and geckodriver (0.26.0) to latest versions.

### CODE REVIEW

**Comment by kingthorin** [comment]
Build failures on java 8/9. Waiting on feedback before merge.

**Comment by thc202** [comment]
It seems Firefox is crashing (sometimes), e.g.:
```
[Parent 7509, Gecko_IOThread] WARNING: pipe error (55): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 7509, Gecko_IOThread] WARNING: pipe error: Broken pipe: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 709
[Parent 7509, Gecko_IOThread] WARNING: pipe error (48): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
###!!! [Parent][MessageChannel] Error: (msgtype=0x15007F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
[Parent 7509, Gecko_IOThread] WARNING: pipe error: Broken pipe: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 709
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
09:59:52.374 [pool-19-thread-2] ERROR c.c.b.WebDriverBackedEmbeddedBrowser - Handling of PopUp windows failed
```
this was already happening with older geckodriver though. Let me try with Firefox nightly.

**Comment by psiinon** [comment]
Worth trying with geckodriver 21? https://github.com/mozilla/geckodriver/releases

**Comment by thc202** [comment]
This PR is to update to that one.

**Comment by psiinon** [comment]
Doh!

**Comment by thc202** [comment]
Still failing with nightly, will report that.

**Comment by VR51** [comment]
I apologise for adding this error here. You have Issues disabled for this fork.

## The Issue

I'm not familiar with Maven. I have looked for a solution but I'm not able to find one. Whenever I enter the root directory for this version of Crawljax and type `maven clean package` I get the following Warnings and Errors:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Crawljax web interface 3.8-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.zaproxy.crawljax:crawljax-core:jar:3.8-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.zaproxy.crawljax.plugins:crawloverview-plugin:jar:3.8-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.zaproxy.crawljax.plugins:test-plugin:jar:3.8-SNAPSHOT is missing, no dependency information available
```

```
[ERROR] Failed to execute goal on project crawljax-web: Could not resolve dependencies for project org.zaproxy.crawljax:crawljax-web:jar:3.8-SNAPSHOT: The following artifacts could not be resolved: org.zaproxy.crawljax:crawljax-core:jar:3.8-SNAPSHOT, org.zaproxy.crawljax.plugins:crawloverview-plugin:jar:3.8-SNAPSHOT, org.zaproxy.crawljax.plugins:test-plugin:jar:3.8-SNAPSHOT: Could not find artifact org.zaproxy.crawljax:crawljax-core:jar:3.8-SNAPSHOT
```

I see what those messages are telling me but being unfamiliar with Maven I have absolutely no idea how to resolve them so I can build Crawljax.

Can you give me some pointers, please.

Also, will you be adding your own changelog to this fork?

I've watched Crawljax (the original) for a couple of years. Only recently hopped onto your maintained version.

Thank you.

**Comment by thc202** [comment]
Regarding https://github.com/zaproxy/crawljax/pull/70#issuecomment-400271075, I'm now waiting on https://bugzilla.mozilla.org/show_bug.cgi?id=1433495 to be able to provide the crash report.

**Comment by thc202** [comment]
For the record, the changelog is being updated in #74.

**Comment by thc202** [comment]
Updated Firefox/geckodriver to latest versions, which seem to be working fine now.

**Comment by thc202** [comment]
Merging, build now passing.

**Pull request merged**
