### PR TITLE
Update Selenium library

### PR DESCRIPTION
**Pull request by thc202**
Update Selenium (3.5.3) and Guava (23, same version as Selenium).
Update codebase to not use deprecated code from Selenium and Guava.

Related to zaproxy/zaproxy#3830 - Update to Selenium 3.5

### CODE REVIEW

**Comment by kingthorin** [comment]
Seems build failed..

**Comment by thc202** [comment]
Yeah, it's unrelated to the changes (I'll trigger a rebuild). I started to tackle that concurrency issue, also saw that multiple times (was already a TODO) when running AJAX Spider, sometimes it terminates (reason exhausted) while some of the consumers are still working.

**Comment by thc202** [comment]
Build now passing.

**Comment by kingthorin** [comment]
Tks

**Comment by psiinon** [comment]
Look good, but now has conflicts

**Comment by thc202** [comment]
Resolved.

**Pull request merged**
